name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19
        options: --privileged
        ports:
          - 2375:2375
        env:
          DOCKER_TLS_CERTDIR: ""

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Install dependencies
        run: |
          cd signalr-cosmos-frontend
          npm install
          cd ../SignalRCosmosDemo
          dotnet restore

      - name: Run tests
        run: |
          cd signalr-cosmos-frontend
          npm test -- --passWithNoTests
          cd ../SignalRCosmosDemo
          dotnet test

      - name: Build project
        run: |
          cd signalr-cosmos-frontend
          npm run build
          cd ../SignalRCosmosDemo
          dotnet build

      - name: Deploy
        run: |
          echo "Deploying application..."
          # Add your deployment commands here
